package com.example.dietapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val lightFruit = Color(0xFFFFF4D1)
val lightVegetable = Color(0xFFDFEDD8)
val lightMilk = Color(0xFFC5DAEE)
val lightGrain = Color(0xFFBC9F82 )
val lightProteinSource = Color(0xFFF0B3B3)
val lightAddedFat = Color(0xFFD0BCFF)
val lightKcal = Color(0xFFF0B3B3)
val lightProtein = Color(0xFFD0BCFF)
val lightCarbs = Color(0xFFBC9F82 )
val lightFats = Color(0xFFFFF4D1)
val lightSaturatedFats = Color(0xFFD0BCFF)
val lightFiber = Color(0xFFD0BCFF)
val lightSoil = Color(0xFFD0BCFF)
val darkFruit = Color(0xFFFFCA49)
val darkVegetable = Color(0xFF76AF60)
val darkMilk = Color(0xFFD0BCFF)
val darkGrain = Color(0xFFD0BCFF)
val darkProteinSource = Color(0xFFD0BCFF)
val darkAddedFat = Color(0xFFD0BCFF)
val darkKcal = Color(0xFFD0BCFF)
val darkProtein = Color(0xFFD0BCFF)
val darkCarbs = Color(0xFFD0BCFF)
val darkFats = Color(0xFFD0BCFF)
val darkSaturatedFats = Color(0xFFD0BCFF)
val darkFiber = Color(0xFFD0BCFF)
val darkSoil = Color(0xFFD0BCFF)